name: js-tests

on:
  workflow_call:
  push:
    branches-ignore:
      - "dependabot/npm_and_yarn/*"

jobs:
  compile:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install NPM dependencies
        run: npm install

      - name: Style
        run: npm run lint

      - name: Test
        run: npm run test

      - name: Compile assets
        run: npm run build
